CREATE DATABASE IF NOT EXISTS BaseTP4;
USE BaseTP4;

CREATE TABLE IF NOT EXISTS PERSONNES(
    idPersonne VARCHAR(10) ,
    numSec INT NOT NULL,
    nom VARCHAR(20) NOT NULL,
    prenom VARCHAR(20) NOT NULL,
    dateNai DATE NOT NULL,
    adresse VARCHAR(50) NOT NULL,
    PRIMARY KEY (idPersonne)
);

CREATE TABLE IF NOT EXISTS MODULES(
    codeModule VARCHAR(10) NOT NULL,
    intetule VARCHAR(20) NOT NULL,
    coef INT NOT NULL,
    PRIMARY KEY (codeModule)
);

CREATE TABLE IF NOT EXISTS SUIVRE(
    idEtudiant VARCHAR(10),
    idModule VARCHAR(10),
    note FLOAT,
    PRIMARY KEY (idEtudiant, idModule),
    FOREIGN KEY (idEtudiant) REFERENCES PERSONNES(idPersonne) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (idModule) REFERENCES MODULES(codeModule) ON DELETE RESTRICT ON UPDATE CASCADE
);

ALTER TABLE personnes ENGINE = INNODB;
ALTER TABLE MODULES ENGINE = INNODB;
ALTER TABLE SUIVRE ENGINE = INNODB;

ALTER TABLE modules ADD COLUMN idEnseignant VARCHAR(10);